version: "3.8"

services:
  # nginx:
  #   image: nginx:stable-alpine
  #   ports:
  #     - "5000:80"

  web:
    build:
      context: ./client
      target: development
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - "/app/node_modules"
      - "./client:/app"
    environment:
      - VITE_FIREBASE_API_KEY=AIzaSyAiR_jVXqdkHndgnIzw3COs01uWU4bFGUs
      - NODE_ENV=development
    develop:
      watch:
        - path: ./client/package.json
          action: rebuild
        - path: ./client/package-lock.json
          action: rebuild
        - path: ./client
          target: /app
          action: sync

  api:
    build:
      context: .
      target: development
    ports:
      - "5000:5000"
    command: npm run dev
    restart: unless-stopped
    volumes:
      - "/app/node_modules"
      - ".:/app"
    environment:
      - PORT=5000
      - DATABASE_URL=mongodb+srv://aryankalra:aryankalra@cluster0.w0jcxpf.mongodb.net/blog-app?retryWrites=true&w=majority&appName=Cluster0
      - JWT_SECRET=dsadjkahakjhKJHkj2kjJjka212jkkjas
