version: "3.8"

services:
  # nginx:
  #   image: nginx:stable-alpine
  #   # ports:
  #   #   - "80:80"
  #   # volumes:
  #   #   - ./client/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  #   depends_on:
  #     - api
  #     - web

  web:
    depends_on:
      - api
    build: ./client
    restart: unless-stopped
    # ports:
    #   - "3000:3000"
    environment:
      - VITE_FIREBASE_API_KEY=AIzaSyAiR_jVXqdkHndgnIzw3COs01uWU4bFGUs

  api:
    build: .
    restart: unless-stopped
    # ports:
    #   - "5000:5000"
    environment:
      - PORT=5000
      - DATABASE_URL=mongodb+srv://aryankalra:aryankalra@cluster0.w0jcxpf.mongodb.net/blog-app?retryWrites=true&w=majority&appName=Cluster0
      - JWT_SECRET=dsadjkahakjhKJHkj2kjJjka212jkkjas
