version: "3.8"

services:
  # nginx:
  #   image: nginx:stable-alpine
  #   # ports:
  #   #   - "80:80"
  #   # volumes:
  #   #   - ./client/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  #   depends_on:
  #     - api
  #     - web

  web:
    depends_on:
      - api
    build: ./client
    image: aryankalra363/node-mern-client
    restart: unless-stopped
    # ports:
    #   - "3000:3000"
    environment:
      - VITE_FIREBASE_API_KEY=${YOUR_FIREBASE_API_KEY}

  api:
    build: .
    image: aryankalra363/node-mern-api1
    restart: unless-stopped
    # ports:
    #   - "5000:5000"
    environment:
      - PORT=5000
      - DATABASE_URL=${YOUR_DATABASE_URL}
      - JWT_SECRET=${YOUR_JWT_SECRET_KEY}
