version: "3.8"
services:
  # nginx:
  #   ports:
  #     - "80"
  web:
    build:
      context: ./client
      target: production
    image: aryankalra363/node-mern-client
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NODE_ENV=production

  api:
    build:
      context: .
      target: production
    image: aryankalra363/node-mern-api
    restart: unless-stopped
    ports:
      - "5000"
